# Values in `upstream`` to passthrough to the metrics server chart: https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
upstream:
  domain: bigbang.dev

  image:
    repository: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/metrics-server
    # Overrides the image tag whose default is v{{ .Chart.AppVersion }}
    tag: "v0.8.0"
    pullPolicy: IfNotPresent

  imagePullSecrets:
  - name: private-registry

  nameOverride: "metrics-server"

  serviceAccount:
    automountServiceAccountToken: false

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

  replicas: 2

  # See https://github.com/kubernetes-sigs/metrics-server#scaling
  resources:
    limits:
      cpu: 100m
      memory: 200Mi

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - metrics-server
        topologyKey: "kubernetes.io/hostname"

# -- Values below for /templates/bigbang -->https://repo1.dso.mil/big-bang/product/packages/metrics-server/-/tree/main/chart/templates/bigbang
istio:
  enabled: false
  hardened:
    enabled: false
    customAuthorizationPolicies: []
    # - name: "allow-nothing"
    #   enabled: true
    #   spec: {}
    outboundTrafficPolicyMode: "REGISTRY_ONLY"
    customServiceEntries: []
      # - name: "allow-google"
      #   enabled: true
      #   spec:
      #     hosts:
      #       - google.com
      #     location: MESH_EXTERNAL
      #     ports:
      #       - number: 443
      #         protocol: TLS
      #         name: https
      #     resolution: DNS
    tempo:
      enabled: false
      namespaces:
      - tempo
      principals:
      - cluster.local/ns/tempo/sa/tempo-tempo
  mtls:
    # -- STRICT = Allow only mutual TLS traffic,
    # PERMISSIVE = Allow both plain text and mutual TLS traffic
    mode: STRICT

networkPolicies:
  enabled: false
  controlPlaneCidr: 0.0.0.0/0
  # CIDR range of your kubernetes nodes. Must be an IP CIDR range (x.x.x.x/x). Allows k8s to metrics-server communication.
  # Defaults to include: "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" networks
  nodeCidr: null
  additionalPolicies: []
  openShift:
    enabled: false

bbtests:
  enabled: false
  scripts:
    image: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.32.7
  imagePullSecret: private-registry